# PlatformService -- build
#
# Linux only (plan decision D2). C99 + OpenSSL + SQLite only (D1).
# Warnings are errors: this codebase does not accumulate warning debt.

BIN          := platformservice
BUILD_DIR    := build
SRC_DIR      := src

CC           ?= gcc

# -D_POSIX_C_SOURCE is required because -std=c99 alone hides sigaction,
# strdup, clock_gettime and friends behind feature-test macros.
CPPFLAGS     := -D_POSIX_C_SOURCE=200809L -I$(SRC_DIR)

WARNINGS     := -Wall -Wextra -Werror \
                -Wshadow -Wpointer-arith -Wcast-qual -Wwrite-strings \
                -Wstrict-prototypes -Wmissing-prototypes -Wredundant-decls \
                -Wswitch-enum -Wundef -Wvla

CFLAGS       ?= -O2 -g
CFLAGS       += -std=c99 $(WARNINGS) -fno-common -MMD -MP
LDFLAGS      :=
LDLIBS       := -pthread

PKGS         := openssl sqlite3
CPPFLAGS     += $(shell pkg-config --cflags $(PKGS))
LDLIBS       += $(shell pkg-config --libs $(PKGS))

SRCS         := $(shell find $(SRC_DIR) -name '*.c')
OBJS         := $(SRCS:%.c=$(BUILD_DIR)/%.o)
DEPS         := $(OBJS:.o=.d)

CERT_DIR     := certs
CERT         := $(CERT_DIR)/dev-cert.pem
KEY          := $(CERT_DIR)/dev-key.pem

.PHONY: all clean run check-config dev-cert dev-env check-banned memcheck help

all: $(BUILD_DIR)/$(BIN)

$(BUILD_DIR)/$(BIN): $(OBJS)
	@mkdir -p $(@D)
	$(CC) $(LDFLAGS) $^ $(LDLIBS) -o $@
	@echo "built $@"

$(BUILD_DIR)/%.o: %.c
	@mkdir -p $(@D)
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

-include $(DEPS)

clean:
	rm -rf $(BUILD_DIR)
	@echo "cleaned"

run: all
	./$(BUILD_DIR)/$(BIN) --dev

check-config: all
	./$(BUILD_DIR)/$(BIN) --check-config

## dev-cert -- self-signed certificate for local development.
## The 0600 mode is not cosmetic: startup refuses a world-readable key (plan 7.1).
dev-cert:
	@mkdir -p $(CERT_DIR)
	@if [ -f $(KEY) ]; then \
	    echo "$(KEY) already exists; refusing to overwrite"; \
	else \
	    openssl req -x509 -newkey rsa:2048 -sha256 -days 365 -nodes \
	        -keyout $(KEY) -out $(CERT) \
	        -subj "/CN=localhost/O=PlatformService Dev" \
	        -addext "subjectAltName=DNS:localhost,IP:127.0.0.1" 2>/dev/null; \
	    chmod 600 $(KEY); \
	    chmod 644 $(CERT); \
	    echo "wrote $(CERT) and $(KEY) (key mode 600)"; \
	fi

## dev-env -- generate an untracked .env with a strong secret and bootstrap admin.
## There is deliberately no default password anywhere in this project.
dev-env:
	@if [ -f .env ]; then \
	    echo ".env already exists; refusing to overwrite"; \
	else \
	    { \
	      echo "# Generated by 'make dev-env'. Untracked. Do not commit."; \
	      echo "PS_JWT_SECRET=$$(openssl rand -base64 48)"; \
	      echo "BOOTSTRAP_ADMIN_USERNAME=admin"; \
	      echo "BOOTSTRAP_ADMIN_EMAIL=admin@example.com"; \
	      echo "BOOTSTRAP_ADMIN_PASSWORD=$$(openssl rand -base64 24)"; \
	    } > .env; \
	    chmod 600 .env; \
	    echo "wrote .env (mode 600). Load it with:  set -a; . ./.env; set +a"; \
	fi

## check-banned -- CI gate for unbounded string functions (plan 7.2).
check-banned:
	@./tools/check_banned_functions.sh

memcheck: all
	valgrind --leak-check=full --show-leak-kinds=definite,indirect \
	         --error-exitcode=1 ./$(BUILD_DIR)/$(BIN) --check-config

help:
	@echo "PlatformService"
	@echo "  make               build"
	@echo "  make run           build and run in dev mode"
	@echo "  make check-config  build and validate configuration, then exit"
	@echo "  make dev-cert      generate a self-signed dev certificate"
	@echo "  make dev-env       generate an untracked .env with secrets"
	@echo "  make check-banned  fail on banned unbounded string functions"
	@echo "  make memcheck      run under valgrind"
	@echo "  make clean         remove build output"
